# Generated by Django 5.1 on 2024-09-27 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroom', '0002_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultroom',
            name='current_participants',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='userroom',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userroom',
            name='current_participants',
        ),
        migrations.AddField(
            model_name='userroom',
            name='current_participants',
            field=models.ManyToManyField(blank=True, related_name='participant_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
