# Generated by Django 5.1 on 2024-09-27 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroom', '0003_alter_defaultroom_current_participants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultroom',
            name='current_participants',
        ),
        migrations.AddField(
            model_name='defaultroom',
            name='current_participants',
            field=models.ManyToManyField(blank=True, related_name='user_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
