# Generated by Django 5.1 on 2024-10-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroom', '0004_remove_defaultroom_current_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroom',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
