# Generated by Django 5.1 on 2024-09-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_sub',
            field=models.CharField(max_length=255),
        ),
    ]
